### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by mirh** [xTVaser/pcsx2-rr#13]
Again @gocha @DocSkellington @pocokhc (hope I'm not to bother, otherwise just unsubscribe)
Follows https://github.com/PCSX2/pcsx2/issues/1923

---
Hi. 
I was wondering how much you still have to be considered complete?
AFAIK this is the most recent tas/lua fork of pcsx2, and I (we?) were wondering if you were planning to merge upstream.

**Comment by xTVaser** [comment]
I think a merge with upstream would be ideal.  I don't know of any critically breaking TAS bugs at the moment, and other than #12 Lua seems to be working as well as it has been since it was added (I havnt done much work on the Lua side of things myself, just attempting to fix bugs).

The main concern that comes to my mind before a merge is:
- Documentation / Wiki articles are quite different and not sure where the main PCSX2 guys would want it to live
  - The root readme has been heavily modified in this fork so we would need to break that off into a separate readme.

Other than that, the TAS tools are working and its just quality of life and small bug fixes going forward so I see no reason to hold off on the merge after we figure out the best way to go in terms of the docs.

**Comment by mirh** [comment]
When you want, the honor of a PR is all yours. 

> Documentation / Wiki articles are quite different and not sure where the main PCSX2 guys would want it to live 

Github wikis are like totally unconnected repos AFAIU. 
(guess like "Building from Source" is quite appreciated also)

> I've also kinda heavily modified the main solution file to make building and debugging easier for us, so I would want to exclude that from the merge.

Or you could drop some idea on https://github.com/PCSX2/pcsx2/pull/2342

**Comment by xTVaser** [comment]
Yes wikis are separate repos you're right.  I don't really have any suggestions for the solution files, it was more just me deleting things that were not relevant to debugging these tools.

I'll work on cleaning things up in preparation for that PR soon.
